---
driver:
  name: vagrant

platforms:
- name: debian-7.8
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: centos-6.5

suites:
- name: default
  run_list: ["recipe[bind]"]
  attributes:
    bind:
      masters: [ "127.0.0.1" ]
      zonetype: 'master'
      zones:
        attribute: [ "example.com" ]
      options: [ "check-names slave ignore;", "multi-master yes;", "provide-ixfr yes;", "request-ixfr yes;", "empty-zones-enable no;"]
      server:
        127.0.0.1:
        - 'bogus no;'
