name              'bind'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs/Configures ISC BIND'
version           '3.3.3'
issues_url        'https://github.com/sous-chefs/bind/issues'
source_url        'https://github.com/sous-chefs/bind'
chef_version      '>= 15.3'

supports 'ubuntu'
supports 'redhat'
supports 'centos'
supports 'fedora'
supports 'debian'
