require 'spec_helper'

describe 'bind_test::chroot' do
  context 'on CentOS 7' do
    let(:chef_run) do
      ChefSpec::SoloRunner.new(
        platform: 'centos', version: '7', step_into: %w(
          bind_service bind_config bind_acl
        )
      ).converge(described_recipe)
    end

    include_context 'version_stub'

    it do
      expect(chef_run).to install_package(%w(bind-chroot bind-utils bind-libs))
    end

    it 'creates /var/named/chroot with mode 750 and owner bind' do
      expect(chef_run).to create_directory('/var/named/chroot').with(
        mode: '0750',
        user: 'root',
        group: 'named'
      )
    end

    %w(dev etc var var/log var/run).each do |subdir|
      it "creates #{::File.join('/var/named/chroot', subdir)} with mode 750 and owner named" do
        expect(chef_run).to create_directory(::File.join('/var/named/chroot', subdir)).with(
          mode: '0750',
          user: 'named'
        )
      end
    end

    %w(named.options named.rfc1912.zones).each do |named_file|
      it "renders file #{::File.join('/etc/named', named_file)}" do
        expect(chef_run).to render_file(::File.join('/etc/named', named_file))
      end
    end

    it 'renders file /etc/named.conf with included files' do
      expect(chef_run).to render_file('/etc/named.conf').with_content(%r{include "/etc/named/named.options"})
      expect(chef_run).to render_file('/etc/named.conf').with_content(%r{include "/etc/named/named.rfc1912.zones"})
    end

    %w(named.empty named.loopback named.localhost named.ca).each do |var_file|
      it "it creates cookbook file #{::File.join('/var/named', var_file)}" do
        expect(chef_run).to create_cookbook_file(::File.join('/var/named', var_file))
      end
    end

    %w(data primary secondary).each do |subdir|
      it "creates subdirectory #{::File.join('/var/named', subdir)}" do
        expect(chef_run).to create_directory(::File.join('/var/named', subdir))
      end
    end

    it 'executes generate_rndc_key' do
      expect(chef_run).to run_execute('generate_rndc_key')
    end

    it 'notifies service[named-chroot]' do
      config_template = chef_run.template('/etc/named/named.options')
      expect(config_template).to notify('bind_service[default]').to(:restart)
    end
  end

  context 'on CentOS 8' do
    let(:chef_run) do
      ChefSpec::SoloRunner.new(
        platform: 'centos', version: '8', step_into: %w(
          bind_service bind_config bind_acl bind_primary_zone bind_primary_zone_template bind_secondary_zone bind_forward_zone
        )
      ).converge(described_recipe)
    end

    include_context 'version_stub'

    it 'uses bind_primary_zone resource' do
      expect(chef_run).to create_bind_primary_zone('example.org')
    end

    it 'uses bind_primary_zone_template resource' do
      expect(chef_run).to create_bind_primary_zone_template('sub.example.org')
    end

    it 'uses bind_secondary_zone resource' do
      expect(chef_run).to create_bind_secondary_zone('secondary.example.org')
    end

    it 'uses bind_forward_zone resource' do
      expect(chef_run).to create_bind_forward_zone('forward.example.org')
    end

    it do
      expect(chef_run).to install_package(%w(bind-chroot bind-utils bind-libs))
    end

    it 'renders file /var/named/primary/db.sub.example.org' do
      expect(chef_run).to render_file('/var/named/primary/db.sub.example.org')
    end

    it 'notifies service[named]' do
      config_template = chef_run.template('/etc/named/named.options')
      expect(config_template).to notify('bind_service[default]').to(:restart)
    end

    it 'will render secondary with no options' do
      stanza = <<~EOF
        # Generated by Chef for fauxhai.local
        # Local modifications will be overwritten.

        include "/etc/named/named.options";
        include "/etc/named/named.rfc1912.zones";

        zone "example.org" IN {
          type master;
          file "primary/db.example.org";
        };
        zone "sub.example.org" IN {
          type master;
          file "primary/db.sub.example.org";
        };

        zone "secondary.example.org" IN {
          type slave;
          file "secondary/db.secondary.example.org";
          masters { 1.1.1.1; 1.1.1.2; };
        };

        zone "forward.example.org" IN {
          type forward;
          forwarders { 1.1.1.1; 1.1.1.2; };
          forward only;
        };

        zone "." IN {
          type hint;
          file "named.ca";
        };
      EOF
      expect(chef_run).to render_file('/etc/named.conf').with_content { |content|
        expect(content).to include stanza
      }
    end
  end

  context 'on Ubuntu 18.04' do
    let(:chef_run) do
      ChefSpec::SoloRunner.new(
        platform: 'ubuntu', version: '18.04', step_into: %w(
          bind_service bind_config bind_acl
        )
      ).converge(described_recipe)
    end

    include_context 'version_stub'

    it do
      expect(chef_run).to install_package(%w(bind9 bind9-host bind9utils dnsutils))
    end

    it 'creates /var/bind9/chroot with mode 750 and owner bind' do
      expect(chef_run).to create_directory('/var/bind9/chroot').with(
        mode: '0750',
        user: 'root',
        group: 'bind'
      )
    end

    %w(dev etc var var/log var/run).each do |subdir|
      it "creates #{::File.join('/var/bind9/chroot', subdir)} with mode 750 and owner bind" do
        expect(chef_run).to create_directory(::File.join('/var/bind9/chroot', subdir)).with(
          mode: '0750',
          user: 'bind'
        )
      end
    end

    it 'creates /var/bind9/chroot/var/cache/bind with mode 750 and owner bind' do
      expect(chef_run).to create_directory('/var/bind9/chroot/var/cache/bind').with(
        mode: '0750',
        user: 'bind'
      )
    end

    it 'creates /var/bind9/chroot/var/cache/bind/dynamic with mode 750 and owner bind' do
      expect(chef_run).to create_directory('/var/bind9/chroot/var/cache/bind/dynamic').with(
        mode: '0750',
        user: 'bind'
      )
    end

    it 'creates /var/bind9/chroot/etc/bind with mode 750 and owner bind' do
      expect(chef_run).to create_directory('/var/bind9/chroot/etc/bind').with(
        mode: '0750',
        user: 'bind'
      )
    end

    it 'renders file /var/bind9/chroot/etc/bind/named.options' do
      expect(chef_run).to render_file('/var/bind9/chroot/etc/bind/named.options')
    end

    it 'renders file /var/bind9/chroot/etc/bind/named.rfc1912.zones' do
      expect(chef_run).to create_cookbook_file('/var/bind9/chroot/etc/bind/named.rfc1912.zones')
    end

    it 'renders file /var/bind9/chroot/etc/bind/named.conf with included files' do
      expect(chef_run).to render_file('/var/bind9/chroot/etc/bind/named.conf').with_content(%r{include "/etc/bind/named.options"})
      expect(chef_run).to render_file('/var/bind9/chroot/etc/bind/named.conf').with_content(%r{include "/etc/bind/named.rfc1912.zones"})
    end

    %w(named.empty named.loopback named.localhost named.ca).each do |var_file|
      it "it creates cookbook file /var/bind9/chroot/var/cache/bind/#{var_file}" do
        expect(chef_run).to create_cookbook_file("/var/bind9/chroot/var/cache/bind/#{var_file}")
      end
    end

    %w(data primary secondary).each do |subdir|
      it "creates subdirectory /var/bind9/chroot/var/cache/bind/#{subdir}" do
        expect(chef_run).to create_directory("/var/bind9/chroot/var/cache/bind/#{subdir}")
      end
    end

    it 'renders file /etc/default/bind9' do
      expect(chef_run).to render_file('/etc/default/bind9')
    end

    %w(null random urandom).each do |d|
      it "executes mknod #{::File.join('/var/bind9/chroot/dev', d)}" do
        expect(chef_run).to run_execute("mknod_#{d}")
      end

      it "doesn't execute chmod on #{::File.join('/var/bind9/chroot/dev', d)}" do
        expect(chef_run).to_not run_execute("chmod_dev_#{d}")
      end

      it "doesn't execute chgrp on #{::File.join('/var/bind9/chroot/dev', d)}" do
        expect(chef_run).to_not run_execute("chgrp_dev_#{d}")
      end
    end

    it 'executes generate_rndc_key' do
      expect(chef_run).to run_execute('generate_rndc_key')
    end

    it 'notifies service[bind]' do
      config_template = chef_run.template('/var/bind9/chroot/etc/bind/named.options')
      expect(config_template).to notify('bind_service[default]').to(:restart)
    end
  end
end
